nix:
  enable: true
  shell-file: shell.nix

templates:
  params:
    author-email: mckean.kylej@gmail.com
    author-name: Kyle McKean
    copyright: 2016 Kyle McKean
    github-username: mckeankylej
    category: Development
